### ISSUE TITLE
Control Sources Packaged into Component-Preload.js

### ISSUE THREAD

**Issue by cschuff** [SAP/ui5-builder#202]
## Expected Behavior
I want to be able to control which files are assembled into Component-preload.js via the projects config (`ui5.yaml`).

## Current Behavior
If found that the task `@ui5/builder.tasks.generateComponentPreload` has a parameter `paths` that can be used for that purpose but I can't find anything on the expected format nor can I manage to force it to do what I want...
I'm trying to achieve something like this (exclude folder `localService` from preload):
```yaml
specVersion: '1.0'
metadata:
  name: test
  namespace: "my.test.namespace"
type: application
builder:
  componentPreload:
    namespaces:
      - "my.test.namespace"
    paths:
      - "**/*.js"
      - "**/!localService/**/*"
```

## Console Output

> ERR! builder:builder Build failed in 17 s
> Error: Resource /resources/my.test.namespace/Component-preload.js has no content
>     at Resource.getStream (node_modules/@ui5/cli/node_modules/@ui5/fs/lib/Resource.js:173:10)
>     at Promise (node_modules/@ui5/cli/node_modules/@ui5/fs/lib/adapters/FileSystem.js:223:14)
>     at new Promise (<anonymous>)
>     at FileSystem._write (node_modules/@ui5/cli/node_modules/@ui5/fs/lib/adapters/FileSystem.js:199:10)
>     at <anonymous>

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)
