### ISSUE TITLE
Option to only build certain dependencies

### ISSUE THREAD

**Issue by sebbi08** [SAP/ui5-builder#204]
## Expected Behavior
There sould be an posibility to build only certen Dependencies and not onyl all

## Current Behavior
it is only possible to ignore some dependencies in dev mode

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.2.1`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

The originated problem is that we have a shim for @babel/polyfill

```
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
    name: babel-polyfills
shims:
    configurations:
        "@babel/polyfill": # name as defined in package.json
            specVersion: "1.0"
            type: module # Use module type
            metadata:
                name: "babel-polyfills"
            resources:
                configuration:
                    paths:
                        /lib/babel/: "dist"
```
when building we want to build this shim but not all other dependencies. that way we could just zip the dist folder and upload that to the SAP Gateway

**Comment by RandomByte** [comment]
This makes sense. We could add a CLI parameter like `--build-dependency="@babel/polyfill"`. Would that match your expectation?

**Comment by sebbi08** [comment]
yea that would be nice but also somehow an configuration option in the yaml file would be nice because when adding another parameter in the end we will have and unreadable npm command.

**Comment by RandomByte** [comment]
So this dependency can be understood as something the application can't work without?

If yes, I agree that a ui5.yaml configuration would make sense as well. It could define a list of dependencies that must be built when the main project is being built (e.g. via `ui5 build`).

**Comment by sebbi08** [comment]
also it would be nice since this dependencie is now allocated via the component namescpce. That it would be included in the Component-preload.js

**Comment by jonaszuberbuehler** [comment]
@sebbi08 Is there a workaround you are currently using when deploying from Web IDE to an ABAP repo?

**Comment by sebbi08** [comment]
our workaround was to delete all the unwanted dependencies inside the dist folder before deploying this was only possible with using grunt and from runt utilize the ui5 tooling

**Comment by jonaszuberbuehler** [comment]
@sebbi08 Ok. I played around a bit with the builder extensions and now I'm copying the defined shims to the dist folder (I'm using core-js-bundle as polyfill):

`ui5.yaml`:

```yaml
---
specVersion: '1.0'
kind: extension
type: task
metadata:
  name: copy-shims
task:
  path: lib/copyShims.js
---
```

`copyShims.js`:

```js
const log = require('@ui5/logger').getLogger('builder:customtask:copy-shim');

/**
 * Custom task example
 *
 * @param {Object} parameters Parameters
 * @param {module:@ui5/fs.DuplexCollection} parameters.workspace DuplexCollection to read and write files
 * @param {module:@ui5/fs.AbstractReader} parameters.dependencies Reader or Collection to read dependency files
 * @param {Object} parameters.options Options
 * @param {string} parameters.options.projectName Project name
 * @param {string} [parameters.options.configuration] Task configuration if given in ui5.yaml
 * @returns {Promise<undefined>} Promise resolving with <code>undefined</code> once data has been written
 */
module.exports = async function ({workspace, dependencies, options}) {
    const shims = await dependencies.byGlob('/resources/thirdparty/*.js');
    await Promise.all(shims.map((resource) => {
        log.info(`Writing file ${resource.getPath()}`);
        workspace.write(resource);
    }));
};
```

`manifest.json`:

```json
"resources": {
    "css": [
        {
            "uri": "css/style.css"
        }
    ],
    "js": [
        {
            "uri": "resources/thirdparty/minified.js"
        }
    ]
}
```

This could of course be improved but it works for me right now. Maybe useful for you too.

**Comment by matz3** [comment]
Looks like a valid workaround. But we are definitely looking into providing a better solution for such use cases.
@jonaszuberbuehler: I think you missed a `return` statement when writing the files (`return workspace.write(resource);`), so that the Promise.all will wait for that.

**Comment by jonaszuberbuehler** [comment]
@matz3 True, thx, good catch!

**Comment by RandomByte** [comment]
@jonaszuberbuehler that's a nice workaround 👍 

Thanks for raising our attention again on this issue. Various people also requested this feature on UI5con last Friday (cc @srenwickblum).

We discussed this with some of the team today and think a ui5.yaml configuration would make sense.

### Proposal
`ui5.yaml`:
```yaml
specVersion: '1.0'
metadata:
  name: my-app
type: application
requiredProjects: # <------------------
  - babel-polyfills # metadata.name of the project
---
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
    name: babel-polyfill-shims
shims:
    configurations:
        "@babel/polyfill":
            specVersion: "1.0"
            type: module
            metadata:
                name: babel-polyfills
            resources:
                configuration:
                    paths:
                        /lib/babel/: "dist"
```


`package.json`:
```json
{
  "name": "my-app",
  "dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@openui5/sap.m": "^1.67.1",
    "@openui5/sap.ui.core": "^1.67.1",
    "@openui5/themelib_sap_fiori_3": "^1.67.1"
  }
}

```

`ui5 build`: Builds my-app and babel-polyfills  
`ui5 build --all`: Builds my-app, babel-polyfills, sap.m, sap.ui.core and themelib_sap_fiori_3

**Comment by jonaszuberbuehler** [comment]
@RandomByte Nice!

Two questions:
- We probably shouldn't be using babel/polyfill anymore (deprecated since 7.4.0 https://babeljs.io/docs/en/babel-polyfill), right?
- Do we have to specify the shim in `manifest.json` as js resource (the way I did it)? This is somehow unclear to me. What are best practices here?

**Comment by RandomByte** [comment]
> We probably shouldn't be using babel/polyfill anymore (deprecated since 7.4.0 https://babeljs.io/docs/en/babel-polyfill), right?

Yes, I saw that as well. I just wanted to stick to the [example](https://github.com/SAP/ui5-builder/issues/204#issue-418206563) given by Sebastian.

> Do we have to specify the shim in manifest.json as js resource (the way I did it)? This is somehow unclear to me. What are best practices here?

No. This is up to how you want to load the resource. The manifest.json configuration will simply lead to the resources being loaded synchronously upon Component initialization. If you want that, use it. However, I would recommend loading the resource asynchronously using our require APIs somewhere in your application or by other means (i.e. script tag in index.html).  
The manifest.json resources configuration does *not* lead to the referenced resources being bundled.

**Comment by jonaszuberbuehler** [comment]
@RandomByte Thanks for the clarification!

**Comment by srenwickblum** [comment]
In the documented example 
```
specVersion: "1.0"
type: application
metadata:
  name: my.application
--- # Everything below this line could also be put into the ui5.yaml of a standalone extension module
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
  name: my.application.thirdparty
shims:
  configurations:
    lodash: # name as defined in package.json
      specVersion: "1.0"
      type: module # Use module type
      metadata:
        name: lodash
      resources:
        configuration:
          paths:
            /resources/my/application/thirdparty/: "" # map root directory of lodash module
```
what is not pointed out is that EVERYTHING is copied across and not just the main file declared in the lodash package.json:
```
...
  "main": "lodash.js",
  "name": "lodash",
...
```
The paths can save a lot of boilerplate code in some cases, but I doubt very much that developers wish to include every js file found in a node_module. It would be nice if I could specifically (instead of a 'catch-all' path) have a "files" section. E.g.
```
specVersion: "1.0"
type: application
metadata:
  name: my.application
--- # Everything below this line could also be put into the ui5.yaml of a standalone extension module
specVersion: "1.0"
kind: extension
type: project-shim
metadata:
  name: my.application.thirdparty
shims:
  configurations:
    lodash: # name as defined in package.json
      specVersion: "1.0"
      type: module # Use module type
      metadata:
        name: lodash
      resources:
        configuration:
          files:
            /resources/my/application/thirdparty/lodash/lodash.js: "/lodash.js"
```
I also like the idea that the file defined in the thirdparty's package.json as the main file, is included by default. In otherwords, when resources section in the ui5.yaml is omitted. Then ui5-tooling creates the minified + -dbg.js versions so when not in debug mode, its business as usual (everything minified) but when developers need to debug, all files are readable, including the thirdparty libraries.

I had also hoped for a way to _optionally_ include this single file from the thirdparty library in the component-preload to optimise the loading times in cases where I'm sure I need the library early during startup. It would of course be nice when I have control to choose whether this is bundled in the preload or not. 

Right now my only practical choice is to manually copy the specific files I need from node_modules and drop them in a "libs" folder which is automatically swallowed up by the build process. But for me this kinda defeats the purpose of ui5Tooling-build - at least a major aspect of it.

**Comment by RandomByte** [comment]
Hey @srenwickblum,
I think this is a bit off-topic. However, you should be able to use the [`builder.resources.excludes`](https://sap.github.io/ui5-tooling/pages/Configuration/#builder-optional) configuration to exclude everything but lodash.js. With this, when using `ui5 serve` (= development) you would still have all resources of the lodash module available.

We don't make much use of package.json configuration because it might mean something different depending on the package. Yet it would add another layer of complexity to a projects configuration.

**Comment by RandomByte** [comment]
In https://github.com/SAP/ui5-builder/pull/380 @kristian contributed a low level API that might resolve some use cases related to this topic.

The question now is how we expose this on a CLI and/or `ui5.yaml` level. I have compiled the following proposal which combines a new `ui5.yaml` configuration with new CLI parameters to hopefully allow solving most use cases. **Any feedback would be greatly appreciated.**

## Proposal
### New ui5.yaml configuration `builder.requiredProjects`

As [proposed earlier](https://github.com/SAP/ui5-builder/issues/204#issuecomment-508387478), all listed projects are always built when the project is being built.

This is useful for scenarios where a dependency is exclusively used by the project itself (no reuse) and can therefore be viewed as being a part of the project.

### New CLI parameters `--include-dependency`, `--include-dependency-regexp`, `--exclude-dependency`, `--exclude-dependency-regexp`

Similar to the already existing [`--include-task/--exclude-task` parameters](https://sap.github.io/ui5-tooling/pages/CLI/#build), they can include or exclude dependencies from the build.

This can be used to craft custom builds where some dependencies might not be required or are already given by the environment.

`--all` will act as an alias for `--include-dependency="*"` (including all dependencies). Omitting it is an alias for `--exclude-dependency="*"` (excluding all dependencies).

The `[...]-regexp=` variants allow specifying a regex that will be matched with the `metadata.name` property of the projects. This allows to include or exclude groups of dependencies based on their namespace.

<img width="960" alt="Concept build selected dependencies" src="https://user-images.githubusercontent.com/1589939/71007414-42e41700-20e7-11ea-8814-2da2f3db6343.png">

**Comment by RandomByte** [comment]
We discussed this in the team today and came up with a change and an enhancement to the initial concept:

<img width="960" alt="Option to only build certain dependencies" src="https://user-images.githubusercontent.com/1589939/81808342-dc411900-951f-11ea-99dd-94402ba74ced.png">

The change is in regards to the ui5.yaml configuration. Instead of providing a new builder configuration `requiredProjects` we would rather offer a `settings` configuration where defaults for the CLI parameters can be set. A similar configuration is already available [for the server](https://sap.github.io/ui5-tooling/pages/Configuration/#server-configuration).

For example if a project wants to always have its dependency "shimmed.thirdparty.library" built, it can configure it in the ui5.yaml like this:

```yaml
builder:
  settings:
     includeDependencies:
      - shimmed.thirdparty.library
```
----

The enhancement is coming from a use case we have with the [JSDoc generation in the OpenUI5 project](https://github.com/SAP/openui5/blob/master/docs/developing.md#building-jsdoc). There, JSDoc is built in a central "testsuite" application which defines dependencies to all OpenUI5 libraries. If a developer makes changes in one of the libraries, all need to be rebuilt because of the lack of this feature. However, since the JSDoc of one library might refer to the JSDoc of a dependency, often this dependency needs to be built as well.

To solve this we would like to include the possibility to specify that a  transitive dependencies should be built as well. Two possible solutions are outlined in this picture. We eventually want to go with one or the other, not both:
<img width="960" alt="Building transitive dependencies" src="https://user-images.githubusercontent.com/1589939/81810259-f03a4a00-9522-11ea-96ec-3ac06ba024e0.png">

While *Solution 1* is similar to Mavens [`--also-make`](https://maven.apache.org/ref/3.6.3/maven-embedder/cli.html) CLI parameter, I'm leaning towards *Solution 2* since it allows a finer control over which subtrees should be built. It also allows for use in the ui5.yaml settings configuration without interfering with additionally passed CLI parameters.

----

Bonus question: Should we only respect the ui5.yaml settings configuration of the root project? I.e. if a dependency also defines `includeDependencies` settings, should they be followed or ignored? I think they should be followed in order to align with an earlier statement from me that ["this dependency can be understood as something the application can't work without"](https://github.com/SAP/ui5-builder/issues/204#issuecomment-470455212)

**Comment by kristian** [comment]
If possible to specify multiple `--include-depdenency-subtree` _Solution 2_ is definitely the more flexible one, as w/ _Solution 1_ it would become ambiguous, which dependencies should be built w/o building the subtree, e.g. you'd like to build single dependencies w/ the subtree of another dependency, this would be only supported w/ _Solution 2_ and a combination of the `--include-dependency` and `--include-dependency-subtree` parameters.

I would also like to suggest renaming `--include-dependency-subtree` to `--include-dependency-tree`, as for my perception `tree` would include the root, whereas `subtree` doesn't. In other words:

`--include-dependency-tree=sap.m` equals `--include-dependency=sap.m` and `--include-dependency-subtree=sap.m`

So for he `--include-dependency-tree` is always the expected option to choose. For your bonus question, if possible I would definitely aswer it as "yes", as I guess the goal of this excersie is to make builds reproducible, which can only be guranteed if also the sub-projects `ui5.yaml` settings are respected. However the command line parameters should overrule any settings in sub-projects `ui5.yaml`s, e.g. if I specify to `--exclude-dependency-tree=sap.m`, and a downstream project is using sap.m, it should not be built. That way you could override the behaviour of your bonus question, if needed. I can think of that beeing a use case, in case e.g. you would not like to inlude a certain library into your build, even if a downstream project requires it to be build with it.

Hope this helps and provides some suitable input for the discussion.

**Comment by mauriciolauffer** [comment]
@sebbi08 not sure whether this help you, but I've been using a module I'd created for similar use cases: 
https://www.npmjs.com/package/ui5-task-copy-resources

ui5.yaml config would be something like:
``` yaml
builder:
  customTasks:
  - name: ui5-task-copy-resources
    afterTask: uglify
    configuration:
      includeDependencies: true
      resources:
        - "/lib/babel/**"
```
